name: "Validate devcontainer-feature.json files"
on:
  workflow_dispatch:
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: "Install devcontainer CLI"
        # run: npm install -g @devcontainers/cli
        shell: bash
        run: |
          sudo wget --no-hsts -q -O /usr/bin/devcontainer \
            "https://github.com/trxcllnt/devcontainers-cli/releases/download/v0.29.0-trxcllnt/devcontainer-linux-x64";
          sudo chmod +x /usr/bin/devcontainer;

      - uses: actions/checkout@v3

      - name: "Validate devcontainer-feature.json files"
        uses: devcontainers/action@v1
        with:
          validate-only: "true"
          base-path-to-features: "./src"
